lichess:
  bot_id: "Talbotbot" 
  api_token: "placeholder" 
  threads: 1

talbot:
  model_path: "/Users/User/Projects/talbot/src/training/supervised/v4_hqgames_with_tactics_opmcts/model/chess_ai_model_epoch_20.pth"
  resblocks: 20
  cpuct: 5.0
  batchsize: 32

timing:
  early_game_movetime: 3
  mid_game_threshold: 24
  mid_game_movetime_factor: 25
  mid_game_increment_factor: 0.75
  mid_game_cap_factor: 0.1
  late_game_threshold: 80
  late_game_movetime_factor: 20
  late_game_increment_factor: 0.8
  late_game_cap_factor: 0.15
  buffer_time: 5
  minimum_time: 1


challenges:
  variant: "standard" 
  min_challenge_time: 3
  min_challenge_increment: 2
  challenge_bots: True
  challenge_rated: True
  challenge_interval: 30
  challenge_time_min: 5 
  challenge_increment_sec: 5